apiVersion: v1
kind: Namespace
metadata:
  name: arc-systems
  labels:
    app.kubernetes.io/name: arc-controller
    app.kubernetes.io/component: controller
    app.kubernetes.io/managed-by: ansible
